### ISSUE TITLE
Code review of the STAGING branch

### ISSUE THREAD

**Issue by kmh287** [kmh287/AthleteTrackingAndroid#15]
@azyth

**Comment by azyth** [comment]
So looking this over it looks ok in terms of java code but I really have no idea how it works. most of the files I see have little to no documentation for the functions. Unless these are all just standard android development app functions, and even if they are, it seems like it would be useful to have documentation on them to just briefly describe what they are doing for people looking at it who have never done app dev. I didnt go line by line but i did try to see what the bulk of the code was doing. happy to go over this again after i have someone explain to me how it functions.

**Comment by kmh287** [comment]
Yeah, it's definitely not structured the same way as a Java Desktop project and ti may have been more readable if you had the chance to import it into Android Studio and run it. (I could show you how to do this but it took about an hour when I did it with Mario, Emilio, and Jay last month)

How about I show you the app itself tomorrow while we're working on communication and walk you through the code and hopefully then a lot of it will be clearer.

@N3ar @azyth

**Comment by azyth** [comment]
That sounds like the best option at this point. thanks

**Comment by kmh287** [comment]
I've added some more documentation. We can talk more about it at the meeting today
